### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by elahesharifi**
Adding two podcast

### CODE REVIEW

**Comment by Ashkan-rmk** [comment]
@elahesharifi Why you delete your PR ?!

**Comment by elahesharifi** [comment]
Because I am a newbie, and I am learning

**Comment by Ashkan-rmk** [comment]
@elahesharifi Aha, thanks for your typo fix… you have added a podcast too. We have appreciated to add it again :)

**Comment by elahesharifi** [comment]
Aha, Now I'll add them

**Pull request closed without merging**
